name: Cloud Functions

on:
  push:
    branches: [ ruiyang/feat/cloud_func, master, ruiyang/feat/ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with: 
        python-version: 3.8
    - name: Install dependencies
      working-directory:  ${{env.working-directory}} 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      working-directory:  ${{env.working-directory}} 
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
