name: Frontend-Docker-gcr
on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
    paths:
      - 'frontend/*'
  # Run tests for any PRs.
  pull_request:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    env:
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      BRANCH: ${GITHUB_REF##*/}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      IMAGE: 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      # Build docker image
      - name: Image
        run: |-
          echo "REACT_APP_GOOGLEKEY=20840044614-h4k2pdffbgumpqvri0g1sv5mn4q61q71.apps.googleusercontent.com" > frontend/.env.production
          echo "REACT_APP_URL=https://sonar-survey-rioz6g7rrq-lz.a.run.app/google" >> frontend/.env.production
          docker build frontend/ --file frontend/Dockerfile --tag eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
      #docker build --build-arg -t eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .
      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q
      # Push image to Google Container Registry
      - name: Build
        run: |-
          docker push eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      # - name: Deploy service to Cloud Run
      #   uses: stefda/action-cloud-run@v1.0
      #   with:
      #     image: eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
      #     service: ${{ secrets.SERVICE_NAME }}
      #     project: ${{ secrets.PROJECT_ID }}
      #     region: ${{ secrets.REGION }}
      #     # env: [path-to-env-file]
      #     service key: ${{ secrets.GCLOUD_AUTH }}

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: ${{ eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA }}
          project_id: ${{ secrets.PROJECT_ID }}
          service: ${{ secrets.SERVICE_NAME }}
          region: ${{ secrets.REGION }}
          credentials: ${{ secrets.GCLOUD_AUTH }}

# Following secrets needs to be available in Github Secrets
# SERVICE_NAME=sonar-survey
# PROJECT_ID=sonar-272913
# REGION=europe-north1
# GCLOUD_AUTH= Base64 encoded service acccount