name: Frontend-Docker-GCR
on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - main
    paths:
      - 'frontend/*'
  # Run tests for any PRs.
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    name: Deploy frontend
    runs-on: ubuntu-latest

    env:
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      BRANCH: ${GITHUB_REF##*/}
      SERVICE_NAME: ${{ secrets.FRONTEND_SERVICE_NAME }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      IMAGE: eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      # Build docker image
      - name: Build
        run: |-
          echo "REACT_APP_GOOGLEKEY=20840044614-h4k2pdffbgumpqvri0g1sv5mn4q61q71.apps.googleusercontent.com" > frontend/.env.production
          echo "REACT_APP_URL=https://sonar-survey-rioz6g7rrq-lz.a.run.app/google" >> frontend/.env.production
          docker build frontend/ --file frontend/Dockerfile --tag eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q

      # Push image to Google Container Registry
      - name: Push Image GCR
        run: |-
          docker push eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      - name: Deploy
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region ${{ secrets.REGION }} \
          --image "eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
          --platform "managed" \
          --port "3000" \
          --allow-unauthenticated

# Following secrets needs to be available in Github Secrets
# FRONTEND_SERVICE_NAME=sonar-app
# PROJECT_ID=sonar-272913
# REGION=europe-north1
# GCLOUD_AUTH= Base64 encoded service acccount